package com.hibernate.hibernatebiddingschemamapping;
// Generated Feb 1, 2018 1:11:28 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Category generated by hbm2java
 */
public class Category  implements java.io.Serializable {


     private Integer id;
     private String value;
     private String description;
     private Set products = new HashSet(0);

    public Category() {
    }

	
    public Category(String value) {
        this.value = value;
    }
    public Category(String value, String description, Set products) {
       this.value = value;
       this.description = description;
       this.products = products;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Set getProducts() {
        return this.products;
    }
    
    public void setProducts(Set products) {
        this.products = products;
    }




}


